# Generated by Django 3.1.5 on 2021-01-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('xml', models.FileField(blank=True, upload_to='xmls/')),
            ],
            options={
                'verbose_name': 'Xml',
                'verbose_name_plural': 'Xmls',
                'ordering': ['id'],
            },
        ),
    ]
