# Generated by Django 3.1.5 on 2021-01-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('nfe_id', models.CharField(max_length=50)),
                ('emit_cnpj', models.CharField(max_length=50)),
                ('emit_name', models.CharField(max_length=50)),
                ('dest_cnpj', models.CharField(max_length=50)),
                ('dest_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'NFe',
                'verbose_name_plural': 'NFes',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='xmlfile',
            options={'ordering': ['id'], 'verbose_name': 'XML', 'verbose_name_plural': 'XMLs'},
        ),
    ]
