# Generated by Django 3.1.5 on 2021-01-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210125_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe',
            name='valor_original_total',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
