# Generated by Django 3.1.5 on 2021-01-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nfe_valor_original_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe',
            name='xml',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xml_info', to='api.xmlfile'),
        ),
    ]
