# Generated by Django 3.1.5 on 2021-01-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.user'),
            preserve_default=False,
        ),
    ]
