# Generated by Django 3.1.5 on 2021-01-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210127_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfe',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='xmlfile',
            name='owner',
        ),
        migrations.AlterField(
            model_name='nfe',
            name='xml',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xml_info', to='api.xmlfile'),
        ),
    ]
