# Generated by Django 3.1.5 on 2021-01-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210127_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe',
            name='exit_date',
            field=models.CharField(default='2020-12-14T19:00:00-03:00', max_length=50),
            preserve_default=False,
        ),
    ]
