# Generated by Django 3.1.5 on 2021-01-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_nfe_exit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='dest_cnpj',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='dest_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='emit_cnpj',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='emit_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='exit_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='nfe_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='valor_original_total',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
