# Generated by Django 3.1.5 on 2021-02-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='dest_cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='dest_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='emit_cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='emit_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='exit_date',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='valor_original_total',
            field=models.FloatField(null=True),
        ),
    ]
