# Generated by Django 3.1.5 on 2021-02-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210201_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='exit_date',
            field=models.DateField(null=True),
        ),
    ]
