# Generated by Django 3.1.5 on 2021-02-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210201_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='nfe',
            name='venc_dates',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='dest_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='emit_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
