# Generated by Django 3.1.6 on 2021-02-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210205_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe',
            name='cnae',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='nfe',
            name='ncm',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
