# Generated by Django 3.1.6 on 2021-02-06 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210206_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfe',
            name='ncm',
        ),
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('cnae', models.BigIntegerField(null=True)),
                ('nfe', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfe_cnae', to='api.nfe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
                'ordering': ['id'],
            },
        ),
    ]
